name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Add Hugging Face Space as a remote repository
      - name: Add remote
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://zohaib1418:$HF@huggingface.co/spaces/zohaib1418/text-summary

      # Step 3: Push the code to the Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force space main
